// Build-time: generate lib/toc.js from data/index.json (embedded, avoids 1601 fetches).
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const idx = JSON.parse(readFileSync(join(process.cwd(), 'data', 'index.json'), 'utf-8'));
const js = `// AUTO-GENERATED by scripts/build-toc.mjs — do not edit.
export const toc = ${JSON.stringify(idx)};
`;
writeFileSync(join(process.cwd(), 'lib', 'toc.js'), js);
console.log('toc.js written:', idx.length, 'entries');
