// Build-time: generate lib/toc.js (LMCK) + lib/toc-nttt.js from indexes.
import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';

const jobs = [
  ['data/index.json', 'lib/toc.js', 'toc'],
  ['data/nttt-index.json', 'lib/toc-nttt.js', 'tocNttt'],
];
for (const [src, dst, name] of jobs) {
  const idx = JSON.parse(readFileSync(join(process.cwd(), src), 'utf-8'));
  const js = `// AUTO-GENERATED by scripts/build-toc.mjs — do not edit.\nexport const ${name} = ${JSON.stringify(idx)};\n`;
  writeFileSync(join(process.cwd(), dst), js);
  console.log(dst, 'written:', idx.length, 'entries');
}
